### ISSUE TITLE
fatal: --author is not 'Name <email>' and matches no existing author

### ISSUE THREAD

**Issue by theJoshMuller** [lwojcik/github-action-feed-to-social-media#35]
Hey Łukasz, thanks for taking the time to build this and make it available! I was excited when I saw it existed!

Having a problem, and I'm feeling silly that I'm not sure how to deal with it, so, sorry if it's got an obvious solution that I've missed somehow.

I've set up the action like I have with other GitHub Actions in the past (in `.github/workflows/`, with a `.yml` file like specified in your README). I've run the workflow, and it keeps failing witt the following:

```
fatal: --author 'theJoshMuller' is not 'Name <email>' and matches no existing author
Error: Process completed with exit code 128.
```

Looks like it's coming from something going on [here](https://github.com/lwojcik/github-action-feed-to-social-media/blob/6c94fec8c94cef870878d52eebbb3a0193612f05/action.yml#L157), as `${{ github.actor }}` would be my username, `theJoshMuller`.

Should I be passing a different author variable, or adding my username as an author in a config somehow?\
Or, do you have any other tips as to why this might not be working for me?

Thanks for the help!

**Comment by lwojcik** [comment]
Hi Josh!

Thanks for letting me know.

This is strange and I haven't seen this happening. I'll check what's up and get back to you.

**Comment by lwojcik** [comment]
I released [v2.4.1](https://github.com/lwojcik/github-action-feed-to-social-media/releases/tag/v2.4.1) that should fix the problem. Please try running the action and let me know if that helps.

To be honest though, I haven't seen this issue popping up in my test setups (even though the error is in line with Git's documented behavior. GitHub action runners are strange beasts).

**Comment by theJoshMuller** [comment]
GitHub action runners are strange beasts indeed.

Still getting an error, but it's a different error, so... progress? 😅

```
remote: Permission to theJoshMuller/theJoshMuller.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/theJoshMuller/theJoshMuller/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```

**Comment by lwojcik** [comment]
Good to know!

About this other error: go to your repo settings, select `Actions` > `General`, look for`Workflow permissions` and see if you have `Read and write permissions` selected.

**Comment by theJoshMuller** [comment]
🤦🏻‍♂️ yup! That did it! Thanks so much! Sorry, still getting the hang of GitHub actions. This one seems obvious in retrospect.😅 

Might be something valuable to add to the README. 

Thanks again!

**Comment by lwojcik** [comment]
I'm glad it helped! And don't worry, we all start somewhere. If I can be of any more help, let me know. 

>Might be something valuable to add to the README.

Good point, I'll do it soon.
